version: "3.3"

services:
  chm.full:
    environment:
      "tag": "latest"
    image: sansob/chm:${tag}
    container_name: chm
    hostname: sansob.chm
    # build:
    #   context: ./curriculum_client
    ports:
      - "9191:9191"
