version: "3.3"

services:
  chm.full:
    #image: "sansob/chm:${TAG:-latest}"
    build: .
    container_name: chm
    hostname: sansob.chm
    # build:
    #   context: ./curriculum_client
    ports:
      - "9191:9191"