name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  IMAGE_NAME: image

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chm:$(date +%s)
    - name: Push the docker to dockerhub
      run: docker push sansob/chm:$(date +%s)
